### ISSUE TITLE
Images getting out from the view.

### ISSUE THREAD

**Issue by Ajit121** [florent37/Flutter-KenBurns#2]
started showing white background while changing position.
KenBurns.multiple(
              minAnimationDuration: Duration(milliseconds: 3000),
              maxAnimationDuration: Duration(milliseconds: 5000),

              maxScale: 1.5,
              children: [
                Image.asset(
                  'assets/img/girl.png',
                  fit: BoxFit.cover,
                ),
                Image.asset(
                  'assets/img/SliderLogin2.png',
                  fit: BoxFit.cover,
                ),
                Image.asset(
                  'assets/img/SliderLogin3.png',
                  fit: BoxFit.cover,
                ),
                Image.asset(
                  'assets/img/SliderLogin4.png',
                  fit: BoxFit.cover,
                ),
              ],
            ),

**Comment by ricard-v** [comment]
This also happens for a single image.

**Comment by sanekyy** [comment]
Fix issue here:

https://github.com/florent37/Flutter-KenBurns/pull/3

**Comment by florent37** [comment]
fixed in 1.0.3, thanks to @sanekyy
