### ISSUE TITLE
_KenBurnsState didn't handle widget update

### ISSUE THREAD

**Issue by sanekyy** [florent37/Flutter-KenBurns#4]
If parent/holder of KenBurns widget will change single to multiple or vise versa there will be some errors related with animation loops and missed handling of widget update.

single -> multiple:
```
#0      List.[] (dart:core-patch/growable_array.dart:177:60)
#1      _KenBurnsState._buildChild (package:kenburns/kenburns.dart:313:63)
#2      _KenBurnsState.build.<anonymous closure> (package:kenburns/kenburns.dart:296:20)
```
multiple -> single
```
NoSuchMethodError: The method '%' was called on null. Receiver: null Tried calling: %()
_KenBurnsState.fire (_KenBurnsState.java:259)
```

I fixed it in PR https://github.com/florent37/Flutter-KenBurns/pull/5.

**Comment by otopba** [comment]
Nice fix!
